### ISSUE TITLE
Allow choosing which share services to use

### ISSUE THREAD

**Issue by fwenzel** [mozilla/SocialShare#17]
Some Mozilla product owners would like to choose which share services to use.

Not sure how to do this (opt-out, probably?) Suggestions welcome :)

**Comment by tallowen** [comment]
@cmoore I think this is won't fix no?

**Comment by cmoore** [comment]
Yea, sure, what the hell.

**Comment by tallowen** [comment]
I agree with @cmoore but @chrismore, what do you think? :P

**Comment by chrismore** [comment]
Yeah, same as what @cmoore said. ;)

I don't see much benefit of picking and choosing services as G+, Facebook, and Twitter are usually the default three now. If that changes, we'll just update the library.
