### ISSUE TITLE
Use for loop?

### ISSUE THREAD

**Issue by darkwing** [mozilla/SocialShare#33]
I just caught this:

https://github.com/mozilla/SocialShare/blob/master/src/socialshare.js#L187

Isn't this just a "getter" when there's no second argument?  Can't it just be removed?

**Comment by alexgibson** [comment]
I might be mistaken, but I believe it acts as a setter here, as it's being passed an object of attribute-value pairs?

https://api.jquery.com/attr/#attr-attributes

**Comment by darkwing** [comment]
Ohhhh, I didn't get that it was an object.  I'm an idiot.

/me fades away
